---
collections:
  - name: ansible.posix
  - name: awx.awx
  - name: community.crypto
  - name: community.general
  - name: community.okd
  - name: infra.controller_configuration
  - name: kubernetes.core
  - name: nutanix.ncp
    version: 1.8.0
