---
collections:
  - name: ansible.posix
  - name: community.crypto
  - name: community.general
  - name: community.okd
  - name: kubernetes.core
  - name: nutanix.ncp # Disabled due to hardcoding pip modules
