---
- name: Get information about a Nutanix VM
  hosts: localhost
  gather_facts: false

  vars:
    vm_name: "MyRHELVM"
    vm_description: "A Red Hat Enterprise Linux VM"

    cluster_name: MyCluster
    subnet_name: MyNetwork

    image_name: rhel-9.2-x86_64-kvm.qcow2

    categories:
      AppType:
        - "OCP_HAPROXY"

  module_defaults:
    nutanix.ncp.ntnx_vms_info:
      nutanix_host: "{{ lookup('ansible.builtin.env', 'NUTANIX_HOSTNAME') }}"
      nutanix_port: "{{ lookup('ansible.builtin.env', 'NUTANIX_PORT') }}"
      nutanix_username: "{{ lookup('ansible.builtin.env', 'NUTANIX_USERNAME') }}"
      nutanix_password: "{{ lookup('ansible.builtin.env', 'NUTANIX_PASSWORD') }}"
      validate_certs: "{{ (lookup('ansible.builtin.env', 'VALIDATE_CERTS') | default('false')) | bool }}"

  tasks:
    - name: Get information about the target VM
      nutanix.ncp.ntnx_vms_info:
        filter:
          vm_name: "{{ vm_name }}"
        kind: vm
      register: vm_result

    - name: Output the VM information
      ansible.builtin.debug:
        var: vm_result
